AWSTemplateFormatVersion: "2010-09-09"
Description: "Amplify and Codecommit create"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "S3 Configuration"
        Parameters:
          - S3BucketName
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  S3BucketName:
    Type: String
    Description : "input code in s3 bucket"
Resources:
# ------------------------------------------------------------#
# 管理画面
# ------------------------------------------------------------#
  RepositoryManagement:
    Type: AWS::CodeCommit::Repository
    Properties:
      Code:
        BranchName: "PRD"
        S3:
          Bucket: !Sub "${S3BucketName}"
          Key: "resouces/eg-iot_management.zip"
      RepositoryName: "eg-iot_management_repository"
      RepositoryDescription: "管理画面"
  AmplifyAppManagement:
      Type: "AWS::Amplify::App"
      Properties:
          AutoBranchCreationConfig:
            EnableAutoBranchCreation: true
            EnableAutoBuild: true
          Name: "eg-iot_management_app"
          Repository: !GetAtt RepositoryManagement.CloneUrlHttp
          IAMServiceRole: !GetAtt IAMRoleForAmplify.Arn
          EnvironmentVariables: 
            - 
              Name: "_LIVE_UPDATES"
              Value: "[{\"pkg\":\"yarn\",\"type\":\"npm\",\"version\":\"latest\"}]"
          CustomRules: 
            - 
              Source: "/<*>"
              Target: "/index.html"
              Status: "404-200"
            - 
              Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>"
              Target: "/index.html"
              Status: "200"
          BuildSpec: |
              version: 1
              frontend:
                phases:
                  preBuild:
                    commands:
                      - yarn install
                  build:
                    commands:
                      - yarn run build
                artifacts:
                  baseDirectory: build
                  files:
                    - '**/*'
                cache:
                  paths:
                    - node_modules/**/*
              
          EnableBranchAutoDeletion: false
          AccessToken: "REPLACEME"
          OauthToken: "REPLACEME"
          CustomHeaders: ""
  AmplifyBranchManagement:
    Type: 'AWS::Amplify::Branch'
    Properties: 
      AppId: !GetAtt AmplifyAppManagement.AppId
      BranchName: "PRD"
      Description: "Management-PRD"
      EnableAutoBuild: true
# ------------------------------------------------------------#
# Top画面
# ------------------------------------------------------------#
  RepositoryTop:
    Type: AWS::CodeCommit::Repository
    Properties:
      Code:
        BranchName: "PRD"
        S3:
          Bucket: !Sub "${S3BucketName}"
          Key: "resouces/eg-iot_top.zip"
      RepositoryName: "eg-iot_top_repository"
      RepositoryDescription: "Top画面"
  AmplifyAppTop:
      Type: "AWS::Amplify::App"
      Properties:
          AutoBranchCreationConfig:
            EnableAutoBranchCreation: true
            EnableAutoBuild: true
          Name: "eg-iot_top_app"
          Repository: !GetAtt RepositoryTop.CloneUrlHttp
          IAMServiceRole: !GetAtt IAMRoleForAmplify.Arn
          CustomRules: 
            - 
              Source: "/<*>"
              Target: "/index.html"
              Status: "404-200"
            - 
              Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>"
              Target: "/index.html"
              Status: "200"
          BuildSpec: |
              version: 1
              frontend:
                phases:
                  preBuild:
                    commands:
                      - yarn install
                  build:
                    commands:
                      - yarn run build
                artifacts:
                  baseDirectory: build
                  files:
                    - '**/*'
                cache:
                  paths:
                    - node_modules/**/*
              
          EnableBranchAutoDeletion: false
          AccessToken: "REPLACEME"
          OauthToken: "REPLACEME"
          CustomHeaders: ""
  AmplifyBranchTop:
    Type: 'AWS::Amplify::Branch'
    Properties: 
      AppId: !GetAtt AmplifyAppTop.AppId
      BranchName: "PRD"
      Description: "Top-PRD"
      EnableAutoBuild: true
# ------------------------------------------------------------#
# IAMRoleForAmplify create
# ------------------------------------------------------------#
  IAMRoleForAmplify:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "amplify.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSCodeCommitFullAccess'
        - 'arn:aws:iam::aws:policy/AdministratorAccess-Amplify'
#        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      MaxSessionDuration: 3600
      Path: "/"
      RoleName: "amplifyRole"

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
#  ManagementView:
#    Value: !GetAtt AmplifyAppManagement.DefaultDomain
#    Export:
#      Name: "ManagementView"
#  TopView:
#    Value: !GetAtt AmplifyAppTop.DefaultDomain
#    Export:
#      Name: "TopView"
# EndPointURL https://{branchName}.{defaultDomain}
  ManagementViewURL:
    Value: !Sub "https://prd.${AmplifyAppManagement.DefaultDomain}"
    Export:
      Name: "ManagementViewURL"
  TopViewURL:
    Value: !Sub "https://prd.${AmplifyAppTop.DefaultDomain}"
    Export:
      Name: "TopViewURL"
      
  RepositoryCloneUrlHttpManagement:
    Value: !GetAtt RepositoryManagement.CloneUrlHttp
    Export:
      Name: "RepositoryCloneUrlHttpManagement"
  RepositoryCloneUrlHttpTop:
    Value: !GetAtt RepositoryTop.CloneUrlHttp
    Export:
      Name: "RepositoryCloneUrlHttpTop"