AWSTemplateFormatVersion: "2010-09-09"
Description: "Amplify and Codecommit create"

Resources:
# ------------------------------------------------------------#
# 管理画面
# ------------------------------------------------------------#
  RepositoryManagement:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: "eg-iot_management_repository"
      RepositoryDescription: "管理画面"
  AmplifyAppManagement:
      Type: "AWS::Amplify::App"
      Properties:
          Name: "eg-iot_management_app"
          Repository: !GetAtt RepositoryManagement.CloneUrlHttp
          IAMServiceRole: !GetAtt IAMRoleForAmplify.Arn
          EnvironmentVariables: 
            - 
              Name: "_LIVE_UPDATES"
              Value: "[{\"pkg\":\"yarn\",\"type\":\"npm\",\"version\":\"latest\"}]"
          BasicAuthConfig: 
              EnableBasicAuth: false
              Username: "dataeg"
              Password: "L3ewcF8D"
          CustomRules: 
            - 
              Source: "/<*>"
              Target: "/index.html"
              Status: "404-200"
            - 
              Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>"
              Target: "/index.html"
              Status: "200"
          BuildSpec: |
              version: 1
              frontend:
                phases:
                  preBuild:
                    commands:
                      - yarn install
                  build:
                    commands:
                      - yarn run build
                artifacts:
                  baseDirectory: build
                  files:
                    - '**/*'
                cache:
                  paths:
                    - node_modules/**/*
              
          EnableBranchAutoDeletion: false
          AccessToken: "REPLACEME"
          OauthToken: "REPLACEME"
          CustomHeaders: ""

# ------------------------------------------------------------#
# Top画面
# ------------------------------------------------------------#
  RepositoryTop:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: "eg-iot_top_repository"
      RepositoryDescription: "Top画面"
  AmplifyAppTop:
      Type: "AWS::Amplify::App"
      Properties:
          Name: "eg-iot_top_app"
          Repository: !GetAtt RepositoryTop.CloneUrlHttp
          IAMServiceRole: !GetAtt IAMRoleForAmplify.Arn
          CustomRules: 
            - 
              Source: "/<*>"
              Target: "/index.html"
              Status: "404-200"
            - 
              Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>"
              Target: "/index.html"
              Status: "200"
          BuildSpec: |
              version: 1
              frontend:
                phases:
                  preBuild:
                    commands:
                      - yarn install
                  build:
                    commands:
                      - yarn run build
                artifacts:
                  baseDirectory: build
                  files:
                    - '**/*'
                cache:
                  paths:
                    - node_modules/**/*
              
          EnableBranchAutoDeletion: false
          AccessToken: "REPLACEME"
          OauthToken: "REPLACEME"
          CustomHeaders: ""
# ------------------------------------------------------------#
# IAMRoleForAmplify create
# ------------------------------------------------------------#
  IAMRoleForAmplify:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "amplify.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess-Amplify'
#        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      MaxSessionDuration: 3600
      Path: "/"
      RoleName: "amplifyRole"

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  ManagementView:
    Value: !GetAtt AmplifyAppManagement.DefaultDomain
    Export:
      Name: "ManagementView"
  TopView:
    Value: !GetAtt AmplifyAppTop.DefaultDomain
    Export:
      Name: "TopView"
      
  RepositoryCloneUrlHttpManagement:
    Value: !GetAtt RepositoryManagement.CloneUrlHttp
    Export:
      Name: "RepositoryCloneUrlHttpManagement"
  RepositoryCloneUrlHttpTop:
    Value: !GetAtt RepositoryTop.CloneUrlHttp
    Export:
      Name: "RepositoryCloneUrlHttpTop"