AWSTemplateFormatVersion: "2010-09-09"
Description: "iot core create"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "IotCore Configuration"
        Parameters:
          - clientNamePrefix
          - deviceId
      - Label:
          default: "S3 Configuration"
        Parameters:
          - s3BucketName
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  clientNamePrefix:
    Type: String
    Default: "budonoki"
    Description : "input clientName"
    
  deviceId:
    Type: String
    Default: "*"
    Description : "input deviceId. default is *"
    
  s3BucketName:
    Type: String
    Default: "eg-iot-budonoki"
    Description : "input s3 bucketName"
    
Resources:
# ------------------------------------------------------------#
# IoTPolicy create DGW二台目以降は手動でResourceを追加
# ------------------------------------------------------------# 
  IoTPolicy:
      Type: "AWS::IoT::Policy"
      Properties:
          PolicyName: !Sub "${clientNamePrefix}-policy"
          PolicyDocument: !Sub |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Action": [
                      "iot:Publish",
                      "iot:Receive"
                    ],
                    "Resource": [
                      "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/mqtt/${clientNamePrefix}/latest"
                    ]
                  },
                  {
                    "Effect": "Allow",
                    "Action": [
                      "iot:Subscribe"
                    ],
                    "Resource": [
                      "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topicfilter/mqtt/${clientNamePrefix}/latest"
                    ]
                  },
                  {
                    "Effect": "Allow",
                    "Action": [
                      "iot:Connect"
                    ],
                    "Resource": [
                      "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:client/${deviceId}"
                    ]
                  }
                ]
              }


# ------------------------------------------------------------#
# IoTRule create
# ------------------------------------------------------------# 
  EdgeRecvMessageTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName : !Sub "${clientNamePrefix}_latest"
      TopicRulePayload:
        AwsIotSqlVersion : "2016-03-23"
        RuleDisabled: false
        Sql: !Sub "SELECT '${s3BucketName}' as clientName , * as receivedMessages FROM 'mqtt/${clientNamePrefix}/latest'"
        Actions:
          - StepFunctions:
              ExecutionNamePrefix : !Sub "${clientNamePrefix}"
              RoleArn: !GetAtt IAMRoleForIotCore.Arn
              StateMachineName: !ImportValue LatestStepFunctionName
          - S3:
              BucketName: !Sub "${s3BucketName}"
              RoleArn: !GetAtt IAMRoleForIotCore.Arn
              Key: "bkstrage/mqtt/${parse_time(\"yyyyMMdd\", timestamp(), \"Asia/Tokyo\" )}/${requestTimeStamp}_${deviceId}.json"

# ------------------------------------------------------------#
# IotCore Role create
# ------------------------------------------------------------#
  IAMRoleForIotCore:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "iot.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambda_FullAccess'
      MaxSessionDuration: 3600
      Path: "/"
      RoleName: !Sub "${clientNamePrefix}-iotCoreRole"
# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  iotCoreRuleName:
    Value: !Ref EdgeRecvMessageTopicRule
    Export:
      Name: "iotCoreRuleName"
  iotCoreTopicName:
    Value: !Sub "mqtt/${clientNamePrefix}/latest"
    Export:
      Name: "iotCoreTopicName"