
# ------------------------------------------------------------#
# DGWからのデータ取込み処理一式
# ------------------------------------------------------------#
  DgwCoreFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: "DGWからのデータ取込み処理一式"
      FunctionName: "dgwCore"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt 
        - IAMRoleForLambda
        - Arn
      Code:
        S3Bucket : !Sub "${S3BucketName}"
        S3Key : "resouces/dgwCore.zip"
      Timeout: 30
      MemorySize: 128
      Runtime: python3.8
      VpcConfig: 
        SubnetIds: 
          - !Sub "${subnetIda}"
          - !Sub "${subnetIdc}"
        SecurityGroupIds: 
          - !Ref LambdaSecurityGroup
      Layers:
        - !Ref LambdaLayer
  DgwCoreVersion:
      Type: "AWS::Lambda::Version"
      Properties:
          Description: "製品化ver1.0"
          FunctionName: !Ref DgwCoreFunction

  DgwCoreAlias:
      Type: "AWS::Lambda::Alias"
      Properties:
          Description: ""
          FunctionName: !Ref DgwCoreFunction
          FunctionVersion: "$LATEST"
          Name: "PRD"
          