AWSTemplateFormatVersion: "2010-09-09"
Description:
  Rabbit MQ Create
  
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Project Name Prefix"
        Parameters:
          - PJPrefix
      - Label:
          default: "VPC Configuration"
        Parameters:
          - privateSubnetId
      - Label:
          default: "MQ Configuration"
        Parameters:
          - MQMasterUserName
          - MQPassword


# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  PJPrefix:
    Type: String
    Default: "eg-iot"

  vpcId:
    Type: 'AWS::EC2::VPC::Id'
  privateSubnetId:
    Type: 'AWS::EC2::Subnet::Id'
    Description : "select private subnet"
    
  MQVersion:
    Type: String
    Default: "3.9.13"
  MQInstanceType:
    Type: String
    Default: "mq.t3.micro"
    
  MQMasterUserName:
    Type: String
    Default: "monone"
#    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "must begin with a letter and contain only alphanumeric characters."
  MQPassword: 
    Default: "mqpasswordHoge123"
    NoEcho: true
    Type: String
    MinLength: 12
    MaxLength: 250
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "must contain only alphanumeric characters."
    
Resources:
# ------------------------------------------------------------#
#  MQBroker create
# ------------------------------------------------------------#
  AmazonMQBroker:
      Type: "AWS::AmazonMQ::Broker"
      Properties:
          AutoMinorVersionUpgrade: true
          BrokerName: !Sub "${PJPrefix}-rabbitMQ-broker"
          DeploymentMode: "SINGLE_INSTANCE"
          EngineType: "RabbitMQ"
          EngineVersion: !Sub "${MQVersion}"
          HostInstanceType: !Sub "${MQInstanceType}"
          PubliclyAccessible: false
          StorageType: "ebs"
          AuthenticationStrategy: "simple"
          MaintenanceWindowStartTime: 
              DayOfWeek: "MONDAY"
              TimeOfDay: "07:00"
              TimeZone: "UTC"
          Logs: 
              General: false
          SecurityGroups:
            - !Ref MQSecurityGroup
          SubnetIds: 
            - !Sub "${privateSubnetId}"
#          EncryptionOptions: 
#              UseAwsOwnedKey: true
          Users: 
            - 
              ConsoleAccess: "true"
              Username: !Sub "${MQMasterUserName}"
              Password: !Sub "${MQPassword}"
              
# ------------------------------------------------------------#
#  SecurityGroup for MQ
# ------------------------------------------------------------#
  MQSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId:  !Sub "${vpcId}"
      GroupName: !Sub "${PJPrefix}-mq-sg"
      GroupDescription: "-"
      Tags:
        - Key: "Name"
          Value: !Sub "${PJPrefix}-mq-sg"
# Rule
      SecurityGroupIngress: 
        - 
          CidrIp: "0.0.0.0/0"
          Description: "AMQP"
          FromPort: 5671
          IpProtocol: "tcp"
          ToPort: 5671
        - 
          CidrIp: "0.0.0.0/0"
          Description: "Web Console"
          FromPort: 443
          IpProtocol: "tcp"
          ToPort: 443
      SecurityGroupEgress: 
        - 
          CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  AmazonMQBrokerResult:
    Value: !Ref AmazonMQBroker
    Export:
      Name: !Sub "${PJPrefix}-AmazonMQBroker"