AWSTemplateFormatVersion: "2010-09-09"
Description: "SecretManager and RDSProxy create"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "proxyName"
        Parameters:
          - proxyName
      - Label:
          default: "RDS Configuration"
        Parameters:
          - DBInstanceName
          - DBMasterUserName
          - DBPassword
          - DBHost
          - DBPort
    ParameterLabels:
      DBInstanceName:
        default: "DBInstanceName"
      DBMasterUserName:
        default: "DBUserName"
      DBPassword:
        default: "DBPassword"
      DBHost:
        default: "DBHost"
      DBPort:
        default: "DBPort"
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  proxyName:
    Type: String
    Default: "budonoki-proxy"
  DBInstanceName:
    Type: String
    Default: "budonoki-rds"
  DBMasterUserName:
    Type: String
    Default: "dbuser"
  DBPassword:
    Type: String
    NoEcho: true
    Default: "dbpassword"
  DBHost:
    Type: String
    Default: "budonoki-rds.c4otf2hm9tqe.ap-northeast-1.rds.amazonaws.com"
  DBPort:
    Type: Number
    Default: 3306
#  vpcId:
#    Type: 'AWS::EC2::VPC::Id'
#  subnetIda:
#    Type: 'AWS::EC2::Subnet::Id'
#    Description : "select public-subnet-a"
#  subnetIdc:
#    Type: 'AWS::EC2::Subnet::Id'
#    Description : "select public-subnet-c"
#  securityGroupId:
#    Type: 'AWS::EC2::SecurityGroup::Id'
#    Description : "select proxy-sg"
Resources:
# ------------------------------------------------------------#
# Resources
# ------------------------------------------------------------# 
  SecretsManagerSecret:
      Type: "AWS::SecretsManager::Secret"
      Properties:
          Name: "budonoki/MySQL"
          Description: "-"
          SecretString: !Sub "{\"username\":\"${DBMasterUserName}\",\"password\":\"${DBPassword}\",\"engine\":\"mysql\",\"host\":\"${DBHost}\",\"port\":${DBPort},\"dbInstanceIdentifier\":\"${DBInstanceName}\"}"

  SampleKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "A sample key"
      KeyPolicy:
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement:
          -
            Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  SecretsManagerSecret:
    Value: !Ref SecretsManagerSecret
    Export:
      Name: "SecretsManagerSecret-ARN"
  SampleKey:
    Value: !GetAtt 
      - SampleKey
      - Arn
    Export:
      Name: "SampleKey-ARN"
